/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Utils.User;
import Utils.dbConnection;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author hirag
 */
public class MainKasir extends javax.swing.JFrame {
    private DefaultTableModel tbl = new DefaultTableModel();
    private List<Integer> idBrg = new ArrayList<>();
    private List<Integer> idBrgTbl = new ArrayList<>();
    private int stok_barang, harga_barang;
    public MainKasir() {
        initComponents();
        this.dispose();
        this.setLocationRelativeTo(null);
        this.setUndecorated(true);
        DefaultTableCellRenderer headRender = new DefaultTableCellRenderer();
        headRender.setForeground(new Color(255,246,244));
        headRender.setBackground(new Color(248,111,3));
        MainTable.getTableHeader().setDefaultRenderer(headRender);
        loadTable();
        loadBarang();
        AutoCompleteDecorator.decorate(barang);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        MainTable = new javax.swing.JTable();
        jPanelExit = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelLog4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        jPanelLog3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        barang = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        totalHar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        totalKem = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        totalBay = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        totalItem = new javax.swing.JTextField();
        jPanelLog5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 246, 244));

        jPanel1.setBackground(new java.awt.Color(255, 246, 244));

        MainTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        MainTable.setSelectionBackground(new java.awt.Color(248, 111, 3));
        jScrollPane2.setViewportView(MainTable);

        jPanelExit.setBackground(new java.awt.Color(255, 0, 51));
        jPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExitMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("X");

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        jPanelLog4.setBackground(new java.awt.Color(255, 0, 51));
        jPanelLog4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLog4MouseClicked(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 246, 244));
        jLabel11.setText("Hapus");

        javax.swing.GroupLayout jPanelLog4Layout = new javax.swing.GroupLayout(jPanelLog4);
        jPanelLog4.setLayout(jPanelLog4Layout);
        jPanelLog4Layout.setHorizontalGroup(
            jPanelLog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(jPanelLog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog4Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        jPanelLog4Layout.setVerticalGroup(
            jPanelLog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanelLog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog4Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jLabel11)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        panel.setBackground(new java.awt.Color(255, 246, 244));
        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(248, 111, 3));
        jLabel13.setText("Nama Barang");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(248, 111, 3));
        jLabel15.setText("Quantity");

        qty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));
        qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtyKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                qtyKeyTyped(evt);
            }
        });

        jPanelLog3.setBackground(new java.awt.Color(248, 111, 3));
        jPanelLog3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLog3MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 246, 244));
        jLabel16.setText("Tambah");

        javax.swing.GroupLayout jPanelLog3Layout = new javax.swing.GroupLayout(jPanelLog3);
        jPanelLog3.setLayout(jPanelLog3Layout);
        jPanelLog3Layout.setHorizontalGroup(
            jPanelLog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(jPanelLog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog3Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        jPanelLog3Layout.setVerticalGroup(
            jPanelLog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanelLog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog3Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        barang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15)
                    .addComponent(qty)
                    .addComponent(barang, 0, 305, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jPanelLog3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelLog3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(barang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 246, 244));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 111, 3)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(248, 111, 3));
        jLabel14.setText("Total Harga");

        totalHar.setEditable(false);
        totalHar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(248, 111, 3));
        jLabel17.setText("Total Item");

        totalKem.setEditable(false);
        totalKem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(248, 111, 3));
        jLabel18.setText("Dibayar");

        totalBay.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));
        totalBay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalBayKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalBayKeyTyped(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(248, 111, 3));
        jLabel19.setText("Kembalian");

        totalItem.setEditable(false);
        totalItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(248, 112, 4)));

        jPanelLog5.setBackground(new java.awt.Color(248, 111, 3));
        jPanelLog5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLog5MouseClicked(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 246, 244));
        jLabel20.setText("Submit");

        javax.swing.GroupLayout jPanelLog5Layout = new javax.swing.GroupLayout(jPanelLog5);
        jPanelLog5.setLayout(jPanelLog5Layout);
        jPanelLog5Layout.setHorizontalGroup(
            jPanelLog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
            .addGroup(jPanelLog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog5Layout.createSequentialGroup()
                    .addGap(0, 27, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 26, Short.MAX_VALUE)))
        );
        jPanelLog5Layout.setVerticalGroup(
            jPanelLog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
            .addGroup(jPanelLog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelLog5Layout.createSequentialGroup()
                    .addGap(0, 7, Short.MAX_VALUE)
                    .addComponent(jLabel20)
                    .addGap(0, 7, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(totalHar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(totalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(totalBay, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                    .addComponent(totalKem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jPanelLog5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelLog5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalBay, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalKem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalItem, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanelLog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanelLog4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
     void loadTable(){
        tbl.addColumn("Nama Barang");
        tbl.addColumn("Harga");
        tbl.addColumn("Quantity");
        tbl.addColumn("Sub Total");
        MainTable.setModel(tbl);
    }
    void loadBarang(){
        DefaultComboBoxModel mdl = new DefaultComboBoxModel();
        try{
            String query = "select * from barang";
            ResultSet rs = dbConnection.getData(query);
            while(rs.next()){
                idBrg.add(rs.getInt("id"));
                mdl.addElement(rs.getString("nama"));
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
        barang.setModel(mdl);
    }
    private void jPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Ingin Menutup Aplikasi?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jPanelExitMouseClicked

    private void jPanelLog4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLog4MouseClicked
        if(MainTable.getSelectedRow() >= 0){
            idBrgTbl.remove(MainTable.getSelectedRow());
            tbl.removeRow(MainTable.getSelectedRow());
        }
    }//GEN-LAST:event_jPanelLog4MouseClicked

    private void qtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyTyped
        char input = evt.getKeyChar();

        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_qtyKeyTyped
    boolean valBar(){
        if(qty.getText().equals("") || qty.getText().equals("0")){
            JOptionPane.showMessageDialog(this, "Quantity Wajib Diisi Dan Tidak Boleh 0");
            return false;
        }
        return true;
    }
    boolean getBarang(){
        String query = "select * from barang where id="+ idBrg.get(barang.getSelectedIndex())+"";
        try{
            ResultSet rs = dbConnection.getData(query);
            rs.next();
            if(rs.getInt("stok") != 0){
                stok_barang = rs.getInt("stok");
                harga_barang = rs.getInt("harga");
            }
            rs.close();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
        return true;
    }
    boolean CheckBar(){
        for(int i = 0; i < idBrgTbl.size(); i++){
            if(idBrg.get(barang.getSelectedIndex()) == idBrgTbl.get(i)){
                String subtotal = String.valueOf(harga_barang * Integer.parseInt(qty.getText()));
                tbl.setValueAt(qty.getText(), i, 2);
                tbl.setValueAt(subtotal, i, 3);
                Calculate();
                return false;
            }
        }
        return true;
    }
     void Calculate(){
        DefaultTableModel tbl = (DefaultTableModel)MainTable.getModel();
        int har = 0;
        int it = 0;
        for(int i = 0; i < tbl.getRowCount(); i++){
            har += Integer.parseInt(tbl.getValueAt(i, 3).toString());
            it += Integer.parseInt(tbl.getValueAt(i, 2).toString());
            totalHar.setText(String.valueOf(har));
            totalItem.setText(String.valueOf(it));
        }
    }
    private void jPanelLog3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLog3MouseClicked
        if(valBar() && getBarang()){
            if(stok_barang >= Integer.parseInt(qty.getText())){
                if(CheckBar()){
                    idBrgTbl.add(idBrg.get(barang.getSelectedIndex()));
                    String nama = barang.getSelectedItem().toString();
                    String harga = String.valueOf(harga_barang);
                    String quantity = qty.getText();
                    String subtotal = String.valueOf(harga_barang * Integer.parseInt(qty.getText()));
                    tbl.addRow(new Object[]{ nama, harga, quantity, subtotal});
                    
                    Calculate();
                    qty.setText("");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Stok Tidak Memenuhi, Sisa Stok adalah " + stok_barang);
            }
        }
    }//GEN-LAST:event_jPanelLog3MouseClicked

    private void totalBayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalBayKeyTyped
        char input = evt.getKeyChar();

        if(!Character.isDigit(input)){
            evt.consume();
        }
    }//GEN-LAST:event_totalBayKeyTyped

    private void jPanelLog5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLog5MouseClicked
        if(totalHar.getText().equals("") || totalKem.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Silahkan Selesaikan Proses Pembayaran Terlebih Dahulu");
        }else{
            LocalDateTime currentDate = LocalDateTime.now();
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
            String formattedDateTime = currentDate.format(formatter);
            String inTran = "insert into transaksi(id_user, total_item, total_harga, total_dibayar, total_kembalian, tanggal) values("+ User.id +", "+ Integer.parseInt(totalItem.getText()) +", "+ Integer.parseInt(totalHar.getText()) +", "+ Integer.parseInt(totalBay.getText()) +", "+ Integer.parseInt(totalKem.getText()) +", '"+ formattedDateTime +"')";
            try{
                Statement stInTran = dbConnection.getConn().createStatement();
                stInTran.executeUpdate(inTran);
                stInTran.close();
                
                String getId = "select id from transaksi order by id desc limit 1";
                ResultSet rs = dbConnection.getData(getId);
                rs.next();
                int idTran = rs.getInt("id");
                
                for(int i = 0; i < MainTable.getRowCount(); i++){
                    String InDetTran = "insert into detail_transaksi(id_transaksi, id_barang, harga, qty, subtotal) values("+ idTran +", "+ idBrgTbl.get(i) +", "+ tbl.getValueAt(i, 1) +", "+ tbl.getValueAt(i, 2) +", "+ tbl.getValueAt(i, 3) +")";
                    Statement stInDetTran = dbConnection.getConn().createStatement();
                    stInDetTran.executeUpdate(InDetTran);
                    stInDetTran.close();
                    
//                    String upStok = "update barang set stok = stok - "+ tbl.getValueAt(i, 2) +" where id = "+ idBrgTbl.get(i) +"";
//                    Statement stUp = dbConnection.getConn().createStatement();
//                    stUp.executeUpdate(upStok);
//                    stUp.close();
                    
                    JOptionPane.showMessageDialog(this, "Transaksi Berhasil");
                    tbl.setRowCount(0);
                    idBrgTbl.clear();
                    totalHar.setText("");
                    totalItem.setText("");
                    totalBay.setText("");
                    totalKem.setText("");
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e.toString());
            }
            
            
        }
    }//GEN-LAST:event_jPanelLog5MouseClicked

    private void totalBayKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalBayKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(Integer.parseInt(totalHar.getText()) <= Integer.parseInt(totalBay.getText())){
                int kembalian = Integer.parseInt(totalBay.getText()) - Integer.parseInt(totalHar.getText());
                totalKem.setText(String.valueOf(kembalian));
            }else{
                JOptionPane.showMessageDialog(this, "Jumlah Uang Yang Dibayarkan Kurang");
            }
        }
    }//GEN-LAST:event_totalBayKeyPressed

    private void qtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtyKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER){
            if(valBar() && getBarang()){
                if(stok_barang >= Integer.parseInt(qty.getText())){
                    if(CheckBar()){
                        idBrgTbl.add(idBrg.get(barang.getSelectedIndex()));
                        String nama = barang.getSelectedItem().toString();
                        String harga = String.valueOf(harga_barang);
                        String quantity = qty.getText();
                        String subtotal = String.valueOf(harga_barang * Integer.parseInt(qty.getText()));
                        tbl.addRow(new Object[]{ nama, harga, quantity, subtotal});

                        Calculate();
                        qty.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Stok Tidak Memenuhi, Sisa Stok adalah " + stok_barang);
                    qty.setText("");
                }
            }
        }
    }//GEN-LAST:event_qtyKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainKasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainKasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable MainTable;
    private javax.swing.JComboBox<String> barang;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelLog3;
    private javax.swing.JPanel jPanelLog4;
    private javax.swing.JPanel jPanelLog5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField qty;
    private javax.swing.JTextField totalBay;
    private javax.swing.JTextField totalHar;
    private javax.swing.JTextField totalItem;
    private javax.swing.JTextField totalKem;
    // End of variables declaration//GEN-END:variables
}
