/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main;

import Utils.User;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hirag
 */
public class MainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MainAdmin
     */
    public MainAdmin() {
        initComponents();
        this.dispose();
        this.setLocationRelativeTo(null);
        this.setUndecorated(true);
        loadDashBoard();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelDash = new javax.swing.JPanel();
        jLabelDash = new javax.swing.JLabel();
        jPanelPeg = new javax.swing.JPanel();
        jLabelPeg = new javax.swing.JLabel();
        jPanelKul = new javax.swing.JPanel();
        jLabelKul = new javax.swing.JLabel();
        jPanelBar = new javax.swing.JPanel();
        jLabelBar = new javax.swing.JLabel();
        jPanelRiwKul = new javax.swing.JPanel();
        jLabelRiwKul = new javax.swing.JLabel();
        jPanelRiwTra = new javax.swing.JPanel();
        jLabelRiwTra = new javax.swing.JLabel();
        Logout = new javax.swing.JPanel();
        jLabelRiwTra2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanelExit = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(248, 111, 3));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/LogoDash.png"))); // NOI18N

        jPanelDash.setBackground(new java.awt.Color(248, 111, 3));
        jPanelDash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelDashMouseClicked(evt);
            }
        });

        jLabelDash.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelDash.setForeground(new java.awt.Color(255, 246, 244));
        jLabelDash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/dashboard.png"))); // NOI18N
        jLabelDash.setText("  Dashboard");

        javax.swing.GroupLayout jPanelDashLayout = new javax.swing.GroupLayout(jPanelDash);
        jPanelDash.setLayout(jPanelDashLayout);
        jPanelDashLayout.setHorizontalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelDash)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelDashLayout.setVerticalGroup(
            jPanelDashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDashLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelDash)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanelPeg.setBackground(new java.awt.Color(248, 111, 3));
        jPanelPeg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelPegMouseClicked(evt);
            }
        });

        jLabelPeg.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelPeg.setForeground(new java.awt.Color(255, 246, 244));
        jLabelPeg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/employees.png"))); // NOI18N
        jLabelPeg.setText("  Pegawai");

        javax.swing.GroupLayout jPanelPegLayout = new javax.swing.GroupLayout(jPanelPeg);
        jPanelPeg.setLayout(jPanelPegLayout);
        jPanelPegLayout.setHorizontalGroup(
            jPanelPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPegLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelPeg)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPegLayout.setVerticalGroup(
            jPanelPegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPegLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabelPeg)
                .addGap(16, 16, 16))
        );

        jPanelKul.setBackground(new java.awt.Color(248, 111, 3));
        jPanelKul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelKulMouseClicked(evt);
            }
        });

        jLabelKul.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelKul.setForeground(new java.awt.Color(255, 246, 244));
        jLabelKul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/packing.png"))); // NOI18N
        jLabelKul.setText("  Kulakan");

        javax.swing.GroupLayout jPanelKulLayout = new javax.swing.GroupLayout(jPanelKul);
        jPanelKul.setLayout(jPanelKulLayout);
        jPanelKulLayout.setHorizontalGroup(
            jPanelKulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKulLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelKul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelKulLayout.setVerticalGroup(
            jPanelKulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKulLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelKul)
                .addGap(18, 18, 18))
        );

        jPanelBar.setBackground(new java.awt.Color(248, 111, 3));
        jPanelBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBarMouseClicked(evt);
            }
        });

        jLabelBar.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelBar.setForeground(new java.awt.Color(255, 246, 244));
        jLabelBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/box.png"))); // NOI18N
        jLabelBar.setText("  Barang");

        javax.swing.GroupLayout jPanelBarLayout = new javax.swing.GroupLayout(jPanelBar);
        jPanelBar.setLayout(jPanelBarLayout);
        jPanelBarLayout.setHorizontalGroup(
            jPanelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelBar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBarLayout.setVerticalGroup(
            jPanelBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBarLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabelBar)
                .addGap(17, 17, 17))
        );

        jPanelRiwKul.setBackground(new java.awt.Color(248, 111, 3));
        jPanelRiwKul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRiwKulMouseClicked(evt);
            }
        });

        jLabelRiwKul.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelRiwKul.setForeground(new java.awt.Color(255, 246, 244));
        jLabelRiwKul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/file.png"))); // NOI18N
        jLabelRiwKul.setText("  Riwayat Kulakan");

        javax.swing.GroupLayout jPanelRiwKulLayout = new javax.swing.GroupLayout(jPanelRiwKul);
        jPanelRiwKul.setLayout(jPanelRiwKulLayout);
        jPanelRiwKulLayout.setHorizontalGroup(
            jPanelRiwKulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRiwKulLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelRiwKul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelRiwKulLayout.setVerticalGroup(
            jPanelRiwKulLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRiwKulLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabelRiwKul)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelRiwTra.setBackground(new java.awt.Color(248, 111, 3));
        jPanelRiwTra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelRiwTraMouseClicked(evt);
            }
        });

        jLabelRiwTra.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelRiwTra.setForeground(new java.awt.Color(255, 246, 244));
        jLabelRiwTra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/trade.png"))); // NOI18N
        jLabelRiwTra.setText("  Riwayat Transaksi");

        javax.swing.GroupLayout jPanelRiwTraLayout = new javax.swing.GroupLayout(jPanelRiwTra);
        jPanelRiwTra.setLayout(jPanelRiwTraLayout);
        jPanelRiwTraLayout.setHorizontalGroup(
            jPanelRiwTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRiwTraLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelRiwTra)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanelRiwTraLayout.setVerticalGroup(
            jPanelRiwTraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRiwTraLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelRiwTra)
                .addGap(18, 18, 18))
        );

        Logout.setBackground(new java.awt.Color(248, 111, 3));
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });

        jLabelRiwTra2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelRiwTra2.setForeground(new java.awt.Color(255, 246, 244));
        jLabelRiwTra2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/logout.png"))); // NOI18N
        jLabelRiwTra2.setText("Logout");

        javax.swing.GroupLayout LogoutLayout = new javax.swing.GroupLayout(Logout);
        Logout.setLayout(LogoutLayout);
        LogoutLayout.setHorizontalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoutLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelRiwTra2)
                .addContainerGap(185, Short.MAX_VALUE))
        );
        LogoutLayout.setVerticalGroup(
            LogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogoutLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabelRiwTra2)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelPeg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelKul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanelRiwKul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelRiwTra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanelDash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelKul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRiwKul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelRiwTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(248, 111, 3));

        jPanelExit.setBackground(new java.awt.Color(255, 0, 51));
        jPanelExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelExitMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("X");

        javax.swing.GroupLayout jPanelExitLayout = new javax.swing.GroupLayout(jPanelExit);
        jPanelExit.setLayout(jPanelExitLayout);
        jPanelExitLayout.setHorizontalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanelExitLayout.setVerticalGroup(
            jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
            .addGroup(jPanelExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelExitLayout.createSequentialGroup()
                    .addGap(0, 4, Short.MAX_VALUE)
                    .addComponent(jLabel5)
                    .addGap(0, 4, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 660, Short.MAX_VALUE)
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanelExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 37, Short.MAX_VALUE))
        );

        MainPanel.setBackground(new java.awt.Color(255, 246, 244));
        MainPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelExitMouseClicked
        int result = JOptionPane.showConfirmDialog(null, "Ingin Menutup Aplikasi?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_jPanelExitMouseClicked
    void loadDashBoard(){
        DashChange();
        
        PegDefault();
        BarDefault();
        KulDefault();
        RiwKulDefault();
        RiwTraDefault();
        
        MainPanel.removeAll();
        DashboardForm form = new DashboardForm();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }
    private void jPanelPegMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelPegMouseClicked
        PegChange();
        
        BarDefault();
        DashDefault();
        KulDefault();
        RiwKulDefault();
        RiwTraDefault();
        
        MainPanel.removeAll();
        MasterPegawai form = new MasterPegawai();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelPegMouseClicked

    private void jPanelDashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelDashMouseClicked
        DashChange();
        
        PegDefault();
        BarDefault();
        KulDefault();
        RiwKulDefault();
        RiwTraDefault();
        
        MainPanel.removeAll();
        DashboardForm form = new DashboardForm();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelDashMouseClicked

    private void jPanelBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBarMouseClicked
        BarChange();
        
        DashDefault();
        PegDefault();
        KulDefault();
        RiwKulDefault();
        RiwTraDefault();
        
        MainPanel.removeAll();
        MasterBarang form = new MasterBarang();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelBarMouseClicked

    private void jPanelKulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelKulMouseClicked
        KulChange();
        
        PegDefault();
        DashDefault();
        BarDefault();
        RiwKulDefault();
        RiwTraDefault();
        
        MainPanel.removeAll();
        KulakanForm form = new KulakanForm();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelKulMouseClicked

    private void jPanelRiwKulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRiwKulMouseClicked
        RiwKulChange();
        
        PegDefault();
        DashDefault();
        KulDefault();
        RiwTraDefault();
        BarDefault();
        
        MainPanel.removeAll();
        RiwayatKulakanForm form = new RiwayatKulakanForm();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelRiwKulMouseClicked

    private void jPanelRiwTraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelRiwTraMouseClicked
        RiwTraChange();

        PegDefault();
        DashDefault();
        KulDefault();
        RiwKulDefault();
        BarDefault();

        MainPanel.removeAll();
        RiwayatTransaksiForm form = new RiwayatTransaksiForm();
        MainPanel.add(form);
        MainPanel.revalidate();
        MainPanel.repaint();
    }//GEN-LAST:event_jPanelRiwTraMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
       int result = JOptionPane.showConfirmDialog(null, "Logout?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION){
            User.setId(0);
            User.setNama("");
            LoginForm form = new LoginForm();
            this.hide();
            form.show();
            form.setVisible(true);
        }
    }//GEN-LAST:event_LogoutMouseClicked
    
    void DashChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/dashboardClicked.png");
        jPanelDash.setBackground(bg);
        jLabelDash.setForeground(ft);
        jLabelDash.setIcon(icon);
    }
    void DashDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/dashboard.png");
        jPanelDash.setBackground(bg);
        jLabelDash.setForeground(ft);
        jLabelDash.setIcon(icon);
    }
    void BarChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/boxClicked.png");
        jPanelBar.setBackground(bg);
        jLabelBar.setForeground(ft);
        jLabelBar.setIcon(icon);
    }
    void BarDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/box.png");
        jPanelBar.setBackground(bg);
        jLabelBar.setForeground(ft);
        jLabelBar.setIcon(icon);
    }
    void PegChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/employeesClicked.png");
        jPanelPeg.setBackground(bg);
        jLabelPeg.setForeground(ft);
        jLabelPeg.setIcon(icon);
    }
    void PegDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/employees.png");
        jPanelPeg.setBackground(bg);
        jLabelPeg.setForeground(ft);
        jLabelPeg.setIcon(icon);
    }
    void KulChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/packingClicked.png");
        jPanelKul.setBackground(bg);
        jLabelKul.setForeground(ft);
        jLabelKul.setIcon(icon);
    }
    void KulDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/packing.png");
        jPanelKul.setBackground(bg);
        jLabelKul.setForeground(ft);
        jLabelKul.setIcon(icon);
    }
    void RiwKulChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/fileClicked.png");
        jPanelRiwKul.setBackground(bg);
        jLabelRiwKul.setForeground(ft);
        jLabelRiwKul.setIcon(icon);
    }
    void RiwKulDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/file.png");
        jPanelRiwKul.setBackground(bg);
        jLabelRiwKul.setForeground(ft);
        jLabelRiwKul.setIcon(icon);
    }
    void RiwTraChange(){
        Color bg = Color.decode("#FFF5F3");
        Color ft = Color.decode("#F87004");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/tradeClicked.png");
        jPanelRiwTra.setBackground(bg);
        jLabelRiwTra.setForeground(ft);
        jLabelRiwTra.setIcon(icon);
    }
    void RiwTraDefault(){
        Color bg = Color.decode("#F87004");
        Color ft = Color.decode("#FFF5F3");
        ImageIcon icon = new ImageIcon("C:/Users/hirag/Documents/NetBeansProjects/Kulaanku/src/asset/trade.png");
        jPanelRiwTra.setBackground(bg);
        jLabelRiwTra.setForeground(ft);
        jLabelRiwTra.setIcon(icon);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logout;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBar;
    private javax.swing.JLabel jLabelDash;
    private javax.swing.JLabel jLabelKul;
    private javax.swing.JLabel jLabelPeg;
    private javax.swing.JLabel jLabelRiwKul;
    private javax.swing.JLabel jLabelRiwTra;
    private javax.swing.JLabel jLabelRiwTra2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelBar;
    private javax.swing.JPanel jPanelDash;
    private javax.swing.JPanel jPanelExit;
    private javax.swing.JPanel jPanelKul;
    private javax.swing.JPanel jPanelPeg;
    private javax.swing.JPanel jPanelRiwKul;
    private javax.swing.JPanel jPanelRiwTra;
    // End of variables declaration//GEN-END:variables
}
